### ISSUE TITLE
Bulk expense amount not correct

### ISSUE THREAD

**Issue by KwanHW** [laughingkid-sg/OneBoard-backend#1]
Response amount is higher than Request
![Request](https://user-images.githubusercontent.com/13163631/126889533-3028ded8-ee1b-455e-9973-52a3e4ea73a3.png)
![Response](https://user-images.githubusercontent.com/13163631/126889541-3182517d-7f84-4442-ad3f-d80cd3dd060a.png)

**Comment by laughingkid-sg** [comment]
Not an issue, data response is correct. See [mongoose-currency](https://www.npmjs.com/package/mongoose-currency) package.

**Comment by laughingkid-sg** [comment]
Not an issue, data response is correct. See [mongoose-currency](https://www.npmjs.com/package/mongoose-currency) package.

**Comment by KwanHW** [comment]
[Fixed on frontend](https://github.com/KwanHW/OneBoard/commit/00916765f693738e2ce15df16ddea19ab6061107)
